# Generated by Django 4.2.19 on 2025-04-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletines_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='estudiante',
            managers=[
            ],
        ),
    ]
